### ISSUE TITLE
Replace the binary format by NIF

### ISSUE THREAD

**Issue by Araq** [microsoft/ifc-spec#156]
See https://github.com/nim-lang/nif/blob/master/doc/nif-spec.md for more details. This 12 pages spec can replace your 251 pages spec while being more extensible, easier to parse and generate and the file sizes should be roughly comparable. If not run a general purpose compression algorithm over the text based format.

**Comment by DarkArc** [comment]
There are a lot of reasons that isn't true.

- The plain text based representation alone will result in the need to as you say, use a compression algorithm.
- I also see absolutely nothing in this format that would allow direct referencing based on file position rather than performing a lookup based on "symbols" that must be discovered (as they can be placed anywhere) and must then be mapped and found via unique identifier.
- In general partial traversal of the AST would be almost certainly slower as effectively everything is variable length and heavily name/lookup dependent.
- The format also lacks _any_ documentation on the contents of "compound nodes", how symbol names should be formed (let alone formed for a language as complicated as C++), etc, and that all _certainly_ lets it be a shorter specification by virtue of being incredibly vague.

A similarly short specification for IFC could almost certainly be formed by removing further details. Meanwhile, the larger issue with IFC is it (as with your specification) could use _more_ documentation and specification to be _more_ vendor agnostic.

**Comment by Araq** [comment]
1. Well for C++ specifically you would need to define a NIF dialect, yes. But that's just a grammar on top of NIF which can be formalized very easily. See for example: https://github.com/nim-lang/nif/blob/master/src/nifc/nifc_grammar.nif
2. Reference based on file position is achieved via a "NIF index" file which is admittedly not yet part of the spec.
3. "almost certainly slower" is just not true IME and I've done my benchmarking for Nim.

You simply cannot come up with a "similarly short specification" for IFC as it conflates the storage mechanism with the data format and special cases everything.

**Comment by DarkArc** [comment]
There is a considerable amount of the specification that exists for Microsoft compiler specific details that is not general. Ideally this will be reduced with time and (in particular) a more vendor neutral expression representation will also be used.

The majority of the specification beyond those details is just defining the node structures.

The difference is comparable to a structured vs unstructured database model.

The grammar for a NIF dialect that you present is extremely incomplete to represent the necessary details for a C++ program. It is also completely lacking any documentation. Once you specify all the unstructured nodes, you'd end up in a very similar position.

On the point of source location information... A goal is that you need not process declarations that are not relevant to the importer. The NIF by virtue of relative source location information cannot meet that goal. Meanwhile in the IFC case, much of the information can be ignored when the importing transition unit does not need it.

**Comment by Araq** [comment]
> The NIF by virtue of relative source location information cannot meet that goal. 

Oh but it does, a NIF index entry contains a starting point source location.

> The majority of the specification beyond those details is just defining the node structures.

But the structures are too irregular to be processed in a generic manner easily.

**Comment by GabrielDosReis** [comment]
See @DarkArc 's comments that I agree with.
I can see a third party tool converting IFC to NIF for those who need it.

**Comment by Araq** [comment]
You don't have any numbers or facts to "agree with" though, you simply don't enjoy your sunk cost falacies. 

But regardless of any of that, how can you even iterate and traverse an IFC file? It's full of special cases.

**Comment by cdacamar** [comment]
> But regardless of any of that, how can you even iterate and traverse an IFC file? It's full of special cases.

That's not true, the data there is intentionally uniform and SoA-based.  All you care about is an index into a partition and an offset.  Then the individual structures themselves are where the actual formatting appears, but even that is fairly uniform.

Take a look at the visualizer code I wrote in JavaScript: https://github.com/microsoft/ifc/tree/main/samples/sgraph-js.  There's really no special cases there, you just need to project over the structures and you descend structure top-down, just like any parser result would produce.  I'm not sure what advantage NIF actually provides here.

**Comment by Araq** [comment]
Well LLVM and wasm have standard text based formats. Text is useful for its debugging, tool development and extensibility benefits.

 NIF is one too with the benefit of column precise line information without causing too much bloat.
